# © 2026 ANSYS, Inc. Unauthorized use, distribution, or duplication is prohibited.

name: Build desktop app

on:
  push:
    branches:
      - main
  workflow_call:  
    outputs:
      artifact-name:
        description: "The name of the uploaded artifact"
        value: ${{ jobs.build.outputs.artifact-name }}
    inputs:
      build-version:
        required: true
        type: string
        default: ""

jobs:
  build:
    name: Build app
    runs-on: windows-latest
    outputs:
      artifact-name: ${{ steps.output-name.outputs.artifact-name }}
      
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: echo event name
        run: echo ${{ github.event_name }}

      - name: Check project version
        if: ${{ github.event_name == 'workflow_call' }}
        run: |
          inputVersion="$(echo ${{inputs.build-version}} | sed "s/v//g")"
          projectVersion=$(cat tauri/src-tauri/Cargo.toml | yq -p toml '.package.version')
          if [ "$inputVersion" = "$projectVersion" ] ; then
            echo "Desktop project version does not match tag version (Desktop project version : $projectVersion)"
            exit 1
          else
            exit 0
          fi

      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_PACKAGES_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Rust
        run: rustup toolchain install

      - name: Cache rust dependencies
        uses: actions/cache@v5
        env:
          base-key: "rust-dependencies"
        with:
          path: |
            ~/.cargo
          key: "${{env.base-key}}-${{ runner.os }}-${{hashFiles('Cargo.lock')}}"
          restore-keys: |
            "${{env.base-key}}-${{ runner.os }}"
            ${{env.base-key}}

      - name: Cache rust artifacts
        uses: actions/cache@v5
        env:
          base-key: "rust-artifacts"
        with:
          path: |
            target
          key: "${{env.base-key}}-${{ runner.os }}-${{hashFiles('frontend/desktop/**')}}"
          restore-keys: |
            "${{env.base-key}}-${{ runner.os }}"
            ${{env.base-key}}

      - name: Add clippy
        run: rustup component add clippy

      - name: Run clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo clippy --no-deps --all-targets --all-features

      - name: Build app
        run: npm run build

      - name: get prefixed artifact
        id: get-prefixed-artifact
        env:
          app_name: "tauri.exe"
        run: |
          if [ ${{inputs.build-version != ''}}] ; then
            echo "app-name=${{inputs.build-version}}-${{env.app_name}}" >> $GITHUB_OUTPUT
          else
            echo "app-name=${{env.app_name}}" >> $GITHUB_OUTPUT
          fi

      - name: Add build version prefix to artifact
        env:
          app_name: "tauri.exe"
        if: ${{inputs.build-version != ''}}
        run: |
          mv target/release/${{ env.app_name }} target/release/"${{ steps.get-prefixed-artifact.outputs.app-name }}"

      - name: upload app
        uses: actions/upload-artifact@v7
        with:
          name: "${{steps.get-prefixed-artifact.outputs.app-name }}"
          path: "target/release/${{steps.get-prefixed-artifact.outputs.app-name }}"

      - id: output-name
        run: echo "artifact-name=${{steps.get-prefixed-artifact.outputs.app-name }}" >> $GITHUB_OUTPUT
