name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_PACKAGES_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Rust
        run: rustup toolchain install

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build app
        run: npm run build

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --latest
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Check tag name
        env:
          TAG: ${{ github.ref_name }}
        run: env

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create $TAG -R "$GITHUB_REPOSITORY" -t $TAG -d -F CHANGELOG.md tauri/src-tauri/target/release/tauri.exe asset.txt
